//idoody.com
//generated at: 8:54:42 PM
function MakeCombo() {
var content = '';
content +='<option value=MDA>ĐH Mỏ địa chất </option>';
content +='<option value=CBK>CĐ Bách khoa Hưng Yên</option>';
content +='<option value=CBV>CĐ Bách Việt</option>';
content +='<option value=CBC>CĐ BC Công nghệ và QTKD</option>';
content +='<option value=CHV>CĐ CNTT Hữu Nghị Việt Hàn</option>';
content +='<option value=CKL>CĐ Cơ khí luyện kim</option>';
content +='<option value=D52>CĐ Cộng đồng Bà Rịa Vũng Tàu</option>';
content +='<option value=d50>CĐ Cộng đồng Đồng Tháp</option>';
content +='<option value=CHN>CĐ Cộng đồng Hà Nội</option>';
content +='<option value=D03>CĐ Cộng đồng Hải Phòng</option>';
content +='<option value=CST>CĐ Cộng đồng Sóc Trăng</option>';
content +='<option value=CCM>CĐ Công nghệ - Dệt may thời trang Hà Nội</option>';
content +='<option value=CBH>CĐ Công nghệ Bắc Hà</option>';
content +='<option value=CDC>CĐ Công nghệ thông tin TPHCM</option>';
content +='<option value=CXD>CĐ Công nghệ và Kinh tế Công nghiệp</option>';
content +='<option value=CCS>CĐ Công nghiệp dệt may TPHCM </option>';
content +='<option value=CCH>CĐ Công nghiệp Huế</option>';
content +='<option value=cci>CĐ Công nghiệp In</option>';
content +='<option value=CND>CĐ Công nghiệp Nam Định</option>';
content +='<option value=CPY>CĐ Công nghiệp Phúc Yên</option>';
content +='<option value=ccd>CĐ Công nghiệp Sao đỏ</option>';
content +='<option value=CCB>CĐ Công nghiệp Thái Nguyên</option>';
content +='<option value=cco>CĐ Công nghiệp Thủ Đức</option>';
content +='<option value=cct>CĐ Công nghiệp thực phẩm TPHCM</option>';
content +='<option value=CCP>CĐ Công nghiệp Tuy Hòa</option>';
content +='<option value=ccx>CĐ Công nghiệp và Xây dựng</option>';
content +='<option value=CIH>CĐ Công nghiệp Việt Hưng</option>';
content +='<option value=CES>CĐ Công thương TpHCM</option>';
content +='<option value=CLD>CĐ Điện Lực Miền Trung</option>';
content +='<option value=CLH>CĐ Điện tử-Điện lạnh Hà Nội</option>';
content +='<option value=CPN>CĐ Đông Phương Đà Nẵng</option>';
content +='<option value=CGS>CĐ Giao thông vận tải 3</option>';
content +='<option value=cgh>CĐ Giao thông vận tải Hà Nội</option>';
content +='<option value=CGT>CĐ Giao thông vận tải TPHCM</option>';
content +='<option value=CHH>CĐ Hàng Hải I</option>';
content +='<option value=CHC>CĐ Hóa chất</option>';
content +='<option value=CKC>CĐ Kĩ thuật Cao Thắng</option>';
content +='<option value=CTN>CĐ Kĩ thuật công nghệ Đồng Nai</option>';
content +='<option value=CKA>CĐ Kinh tế - Kỹ thuật Vĩnh phúc</option>';
content +='<option value=CKT>CĐ Kinh tế - Tài chính Thái Nguyên</option>';
content +='<option value=ckd>CĐ Kinh tế đối ngoại</option>';
content +='<option value=CEA>CĐ kinh tế kĩ thuật Nghệ An</option>';
content +='<option value=CKO>CĐ Kinh tế Kỹ thuật Kon Tum</option>';
content +='<option value=cpp>CĐ Kinh tế Kỹ thuật Phú Thọ</option>';
content +='<option value=CKQ>CĐ Kinh tế kỹ thuật Quảng Nam</option>';
content +='<option value=CTB>CĐ Kinh tế Kỹ thuật Thái Bình</option>';
content +='<option value=cdq>CĐ Kỹ nghệ Đông Á Quảng Nam</option>';
content +='<option value=CVX>CĐ Kỹ thuật - Công nghệ Vạn Xuân</option>';
content +='<option value=CKB>CĐ Kỹ thuật Lý Tự Trọng HCM</option>';
content +='<option value=CKY>CĐ Kỹ thuật Y tế II</option>';
content +='<option value=CTT>CĐ Nguyễn Tất Thành</option>';
content +='<option value=CV1>CĐ Nội vụ</option>';
content +='<option value=CNL>CĐ Nông Lâm</option>';
content +='<option value=CDP>CĐ Nông lâm Đông Bắc</option>';
content +='<option value=CNP>CĐ Nông nghiệp & PTNT Bắc Bộ</option>';
content +='<option value=CPT>CĐ Phát thanh truyền hình 1</option>';
content +='<option value=cpd>CĐ Phương Đông Quảng Nam</option>';
content +='<option value=c62>CĐ Sư phạm Điện Biên</option>';
content +='<option value=C24>CĐ Sư phạm Hà Nam</option>';
content +='<option value=C01>CĐ Sư phạm Hà Nội</option>';
content +='<option value=C20>CĐ Sư phạm Hà Tây</option>';
content +='<option value=C21>CĐ Sư phạm Hải Dương</option>';
content +='<option value=c23>CĐ Sư phạm Hòa Bình</option>';
content +='<option value=C33>CĐ Sư phạm Huế</option>';
content +='<option value=c22>CĐ Sư phạm Hưng Yên</option>';
content +='<option value=c36>CĐ Sư phạm KonTum</option>';
content +='<option value=ck4>CĐ Sư phạm kỹ thuật Vĩnh Long</option>';
content +='<option value=cm3>CĐ Sư phạm mẫu giáo TW3 TPHCM</option>';
content +='<option value=c29>CĐ Sư phạm Nghệ An</option>';
content +='<option value=c41>CĐ Sư phạm Nha Trang</option>';
content +='<option value=c17>CĐ Sư phạm Quảng Ninh</option>';
content +='<option value=c32>CĐ Sư phạm Quảng Trị</option>';
content +='<option value=C59>CĐ Sư phạm Sóc Trăng</option>';
content +='<option value=c14>CĐ Sư phạm Sơn La</option>';
content +='<option value=C46>CĐ Sư phạm Tây Ninh</option>';
content +='<option value=c58>CĐ sư phạm Trà Vinh</option>';
content +='<option value=C57>CĐ Sư phạm Vĩnh Long</option>';
content +='<option value=c16>CĐ Sư phạm Vĩnh Phúc</option>';
content +='<option value=c13>CĐ Sư phạm Yên Bái</option>';
content +='<option value=ctk>CĐ Tài chính - Quản trị Kinh doanh</option>';
content +='<option value=CTS>CĐ Tài chính hải quan</option>';
content +='<option value=CKV>CĐ Tài chính Vĩnh Long</option>';
content +='<option value=CTE>CĐ Thống kê</option>';
content +='<option value=CMS>CĐ Thương Mại</option>';
content +='<option value=CSB>CĐ Thủy sản</option>';
content +='<option value=CDK>CĐ Văn hóa & Nghệ thuật Nha Trang</option>';
content +='<option value=cvl>CĐ Văn hóa nghệ thuật ĐăkLăk</option>';
content +='<option value=cvy>CĐ Văn hóa Nghệ thuật Du lịch Yên Bái</option>';
content +='<option value=CVB>CĐ Văn Hóa Nghệ Thuật Tây Bắc</option>';
content +='<option value=cvn>CĐ Văn hóa nghệ thuật TP HCM</option>';
content +='<option value=cvd>CĐ Văn hóa Nghệ thuật và Du lịch Hạ Long</option>';
content +='<option value=CNV>CĐ Văn hóa Nghệ Thuật Việt Bắc</option>';
content +='<option value=CVV>CD VHNT Nghệ An</option>';
content +='<option value=CDT>CĐ Xây dựng công trình và Đô thị</option>';
content +='<option value=cmt>CĐ Xây dựng miền Tây</option>';
content +='<option value=cx3>CĐ Xây dựng số 3</option>';
content +='<option value=CYH>CĐ Y tế Hà Nam</option>';
content +='<option value=CYZ>CĐ Y Tế Hà Nội</option>';
content +='<option value=cyk>CĐ Y tế Khánh Hòa</option>';
content +='<option value=CYL>CĐ Y tế Lạng Sơn</option>';
content +='<option value=CYU>CĐ Y Tế quảng Nam</option>';
content +='<option value=cyq>CĐ Y tế Quảng Ninh</option>';
content +='<option value=cye>CĐ Y tế Thái Bình</option>';
content +='<option value=cyi>CĐ Y tế Thái Nguyên</option>';
content +='<option value=CM2>CĐSP Trung ương - Nha Trang</option>';
content +='<option value=tag>ĐH An Giang</option>';
content +='<option value=DDK>ĐH Bách Khoa - ĐH Đà Nẵng</option>';
content +='<option value=bka>ĐH Bách khoa Hà Nội</option>';
content +='<option value=QSB>ĐH Bách khoa TPHCM</option>';
content +='<option value=tct>ĐH Cần Thơ</option>';
content +='<option value=css>ĐH Cảnh sát nhân dân</option>';
content +='<option value=QSC>ĐH CNTT- ĐHQG TPHCM</option>';
content +='<option value=lda>ĐH Công Đoàn</option>';
content +='<option value=QHI>ĐH Công nghệ - ĐHQGHN</option>';
content +='<option value=dcn>ĐH Công nghiêp HN</option>';
content +='<option value=ddm>ĐH Công nghiệp Quảng Ninh</option>';
content +='<option value=HUI>ĐH Công nghiệp TPHCM</option>';
content +='<option value=tdl>ĐH Đà Lạt</option>';
content +='<option value=DDY>ĐH Đà Nẵng - Khoa Y</option>';
content +='<option value=DDP>ĐH Đà Nẵng - phân hiệu tại KonTum</option>';
content +='<option value=dkc>ĐH Dân lập Kỹ thuật công nghệ TPHCM</option>';
content +='<option value=dlh>ĐH Dân lập Lạc Hồng</option>';
content +='<option value=ddl>ĐH Điện Lực</option>';
content +='<option value=ydd>ĐH Điều dưỡng Nam Định</option>';
content +='<option value=dkh>ĐH Dược</option>';
content +='<option value=gha>ĐH Giao thông vận tải</option>';
content +='<option value=gsa>ĐH Giao thông vận tải (Cơ sở 2 - GSA)</option>';
content +='<option value=gts>ĐH Giao thông vận tải TPHCM (GTS)</option>';
content +='<option value=nhf>ĐH Hà Nội</option>';
content +='<option value=THP>ĐH Hải Phòng</option>';
content +='<option value=hha>ĐH Hàng Hải</option>';
content +='<option value=DTH>ĐH Hoa Sen</option>';
content +='<option value=HDT>ĐH Hồng Đức</option>';
content +='<option value=DHT>ĐH Huế - ĐH Khoa học </option>';
content +='<option value=DHK>ĐH Huế - ĐH Kinh tế</option>';
content +='<option value=DHN>ĐH Huế - ĐH Nghệ Thuật</option>';
content +='<option value=DHF>ĐH Huế - ĐH Ngoại Ngữ</option>';
content +='<option value=DHL>ĐH Huế - ĐH Nông Lâm</option>';
content +='<option value=DHS>ĐH Huế - ĐH Sư phạm</option>';
content +='<option value=DHY>ĐH Huế - ĐH Y</option>';
content +='<option value=DHD>ĐH Huế - Khoa Du Lịch</option>';
content +='<option value=DHC>ĐH Huế - Khoa Thể chất</option>';
content +='<option value=THV>ĐH Hùng Vương (Phú Thọ)</option>';
content +='<option value=qst>ĐH Khoa học tự nhiên-ĐHQG TPHCM</option>';
content +='<option value=QSX>ĐH Khoa học Xã hội Nhân văn - ĐHQG TPHCM</option>';
content +='<option value=QHX>ĐH Khoa học Xã hội Nhân văn - ĐHQGHN(khối D)</option>';
content +='<option value=QHT>ĐH KHTN - ĐHQGHN</option>';
content +='<option value=KTA>ĐH Kiến Trúc Hà Nội</option>';
content +='<option value=kts>ĐH Kiến Trúc TPHCM</option>';
content +='<option value=dqk>ĐH Kinh doanh và Công nghệ Hà Nội</option>';
content +='<option value=DDQ>ĐH Kinh tế -ĐH Đà nẵng</option>';
content +='<option value=QHE>ĐH Kinh tế- ĐHQGHN(khối A)</option>';
content +='<option value=kha>ĐH Kinh tế Quốc Dân</option>';
content +='<option value=ksa>ĐH Kinh tế TPHCM</option>';
content +='<option value=DTE>ĐH Kinh tế và QTKD - ĐH Thái Nguyên</option>';
content +='<option value=dky>ĐH Kỹ thuật Y tế Hải Dương</option>';
content +='<option value=lnh>ĐH Lâm Nghiệp</option>';
content +='<option value=LNS>ĐH Lâm nghiệp (phía Nam)</option>';
content +='<option value=LPH>ĐH Luật Hà Nội</option>';
content +='<option value=LPS>ĐH Luật TPHCM</option>';
content +='<option value=MBS>ĐH Mở TPHCM</option>';
content +='<option value=MTC>ĐH Mỹ thuật Công nghiệp</option>';
content +='<option value=NHS>ĐH Ngân hàng TPHCM</option>';
content +='<option value=DDF>ĐH Ngoại ngữ - ĐH Đà Nẵng</option>';
content +='<option value=QHF>ĐH Ngoại ngữ - ĐHQGHN</option>';
content +='<option value=nth>ĐH Ngoại thương (cơ sở 1)</option>';
content +='<option value=nts>ĐH Ngoại thương (Cơ sở 2 - NTS)</option>';
content +='<option value=TSB>ĐH Nha Trang (cơ sở Bắc Ninh)</option>';
content +='<option value=TSS>ĐH Nha Trang (cơ sở Cần thơ)</option>';
content +='<option value=TSN>ĐH Nha Trang (cơ sở Nha Trang)</option>';
content +='<option value=nls>ĐH Nông Lâm TPHCM</option>';
content +='<option value=NNH>ĐH Nông nghiệp I</option>';
content +='<option value=dpq>ĐH Phạm Văn Đồng</option>';
content +='<option value=dpy>ĐH Phú Yên</option>';
content +='<option value=dqb>ĐH Quảng Bình</option>';
content +='<option value=dqu>ĐH Quảng Nam</option>';
content +='<option value=QSQ>ĐH Quốc Tế - ĐHQG TPHCM</option>';
content +='<option value=DQN>ĐH Quy Nhơn</option>';
content +='<option value=RHM>ĐH Răng Hàm Mặt</option>';
content +='<option value=sgd>ĐH Sài Gòn</option>';
content +='<option value=spd>ĐH Sư phạm Đồng Tháp</option>';
content +='<option value=SPH2>ĐH Sư phạm Hà Nội</option>';
content +='<option value=SP2>ĐH Sư phạm Hà Nội 2</option>';
content +='<option value=spk>ĐH Sư phạm Kĩ thuật TPHCM</option>';
content +='<option value=SKV>ĐH Sư phạm kỹ thuật Vinh</option>';
content +='<option value=GNT>ĐH Sư phạm Nghệ Thuật Trung Ương</option>';
content +='<option value=tdh>ĐH Sư phạm Thể dục thể thao Hà Tây</option>';
content +='<option value=SPS>ĐH Sư phạm TPHCM</option>';
content +='<option value=DDS>ĐH Sư phạm-ĐH Đà nẵng(khối A,C)</option>';
content +='<option value=dms>ĐH Tài chính Marketing</option>';
content +='<option value=ttb>ĐH Tây Bắc</option>';
content +='<option value=ttn>ĐH Tây Nguyên</option>';
content +='<option value=TDS>ĐH TDTT TPHCM</option>';
content +='<option value=STS>ĐH TDTT TPHCM</option>';
content +='<option value=DTU>ĐH Thái Nguyên - CĐ Kinh tế kĩ thuật</option>';
content +='<option value=DTK>ĐH Thái Nguyên - ĐH Kĩ thuật Công nghiệp</option>';
content +='<option value=DTN>ĐH Thái Nguyên - ĐH Nông Lâm</option>';
content +='<option value=DTS>ĐH Thái Nguyên - ĐH Sư phạm</option>';
content +='<option value=DTY>ĐH Thái Nguyên - ĐH Y Khoa</option>';
content +='<option value=DTC>ĐH Thái Nguyên - Khoa Công nghệ thông tin</option>';
content +='<option value=DTZ>ĐH Thái Nguyên - Khoa KHTN&XH</option>';
content +='<option value=DTF>ĐH Thái Nguyên - Khoa Ngoại ngữ</option>';
content +='<option value=dtl>ĐH Thăng Long</option>';
content +='<option value=CTD>ĐH Thành Đô</option>';
content +='<option value=tdb>ĐH Thể dục thể thao Bắc Ninh</option>';
content +='<option value=ttd>ĐH Thể dục thể thao Đà Nẵng</option>';
content +='<option value=tma>ĐH Thương Mại</option>';
content +='<option value=TLA>ĐH Thủy Lợi (cơ sở 1)</option>';
content +='<option value=TLS>ĐH Thủy Lợi (cơ sở 2)</option>';
content +='<option value=ttg>ĐH Tiền Giang</option>';
content +='<option value=DTT>ĐH Tôn Đức Thắng</option>';
content +='<option value=DVT>ĐH Trà Vinh</option>';
content +='<option value=vhh>ĐH Văn Hóa</option>';
content +='<option value=znh>ĐH Văn Hóa Nghệ Thuật (Hệ Dân sự - Phía Bắc)</option>';
content +='<option value=zns>ĐH Văn hóa Nghệ thuật (Hệ dân sự - Phía Nam)</option>';
content +='<option value=vhs>ĐH Văn hóa TPHCM</option>';
content +='<option value=TDV>ĐH Vinh</option>';
content +='<option value=xda>ĐH Xây Dựng</option>';
content +='<option value=yct>ĐH Y Dược Cần Thơ</option>';
content +='<option value=YDS>ĐH Y dược TPHCM</option>';
content +='<option value=YHB>ĐH Y Hà Nội</option>';
content +='<option value=YPB>ĐH Y Hải Phòng</option>';
content +='<option value=TYS>ĐH Y khoa Phạm Ngọc Thạch</option>';
content +='<option value=ytc>ĐH Y tế Công cộng</option>';
content +='<option value=YTB>ĐH Y Thái Bình</option>';
content +='<option value=HFH>Học Viện Hậu Cần - Hệ Dân sự phía Bắc</option>';
content +='<option value=TGC>HV Báo chí và tuyên truyền</option>';
content +='<option value=bvh>HV Bưu chính (cơ sở phía Bắc)</option>';
content +='<option value=bvs>HV Công nghệ Bưu chính (Cơ sở 2)</option>';
content +='<option value=hhk>HV Hàng không Việt Nam</option>';
content +='<option value=hch>HV Hành chính Quốc gia (Phía Bắc)</option>';
content +='<option value=hcs>HV Hành chính Quốc gia (Phía Nam)</option>';
content +='<option value=kma>HV Kĩ thuật mật mã</option>';
content +='<option value=DQH>HV Kĩ thuật Quân sự(hệ dân sự)</option>';
content +='<option value=DQS>HV Kỹ thuật Quân Sự phía Nam</option>';
content +='<option value=NHH>HV Ngân hàng</option>';
content +='<option value=hqt>HV Ngoại Giao</option>';
content +='<option value=HVQ>HV quản lý giáo dục</option>';
content +='<option value=htc>HV Tài Chính</option>';
content +='<option value=hyd>HV Y Dược cổ truyền</option>';
content +='<option value=qsk>Khoa Kinh tế - ĐHQG TPHCM</option>';
content +='<option value=QHL>Khoa Luật - ĐHQGHN(khối A)</option>';
content +='<option value=QHS>Khoa Sư phạm - ĐHQGHN(khối A,B)</option>';
content +='<option value=dhq>Phân viên Huế tại Quảng trị</option>';
content +='<option value=MHN>Viện ĐH Mở HN</option>';
return content;
}